import { decimal, homes, homesPer1000, mw, people, percent, personsPerHome, requests, signedPeople } from "./formatters.js";

export const views = {
	population: {
		kicker: "Bevolking, samenstelling en jaarstromen",
		title: "Nederland in personen",
		leftLabel: "inwoners",
		rightLabel: "personen per jaar",
		series: [
			{ key: "population", label: "Bevolking", color: "#235789", axis: "left", kind: "line", width: 3 },
			{ key: "populationMinusNetMigration", label: "Bevolking min cum. nettomigratie (gekalibreerd)", color: "#5b4b8a", axis: "left", kind: "line", width: 2, dash: "7 5" },
			{ key: "nativeBackgroundProxy", label: "Inheemse proxy: 2 ouders geboren in NL", color: "#8167a9", axis: "left", kind: "line", width: 2.4, dash: "8 4" },
			{ key: "migrationBackgroundTotal", label: "Migratieachtergrond totaal", color: "#8b443d", axis: "left", kind: "line", width: 2.2, dash: "10 4" },
			{ key: "bornAbroadPopulation", label: "In buitenland geboren", color: "#edae49", axis: "left", kind: "line", width: 2.2, dash: "3 5" },
			{ key: "nativeBackgroundProxyPctPopulation", label: "Inheemse proxy (% bevolking)", color: "#8167a9", axis: "left", kind: "line", width: 2.2, dash: "8 4" },
			{ key: "migrationBackgroundTotalPctPopulation", label: "Migratieachtergrond (%)", color: "#8b443d", axis: "left", kind: "line", width: 2, dash: "10 4" },
			{ key: "bornAbroadPopulationPctPopulation", label: "In buitenland geboren (%)", color: "#edae49", axis: "left", kind: "line", width: 2, dash: "3 5" },
			{ key: "liveBirths", label: "Geboorten", color: "#2a9d8f", axis: "right", kind: "line", width: 2.2 },
			{ key: "deaths", label: "Sterfte", color: "#6c584c", axis: "right", kind: "line", width: 2.2 },
			{ key: "birthSurplus", label: "Geboorteoverschot", color: "#588157", axis: "right", kind: "line", width: 2, dash: "6 4" },
			{ key: "immigration", label: "Immigratie", color: "#d1495b", axis: "right", kind: "bar" },
			{ key: "emigration", label: "Emigratie", color: "#edae49", axis: "right", kind: "bar" },
			{ key: "netMigration", label: "Nettomigratie", color: "#177e89", axis: "right", kind: "line", width: 2.4 },
		],
		stats: [
			{ key: "population", label: "Bevolking", format: people },
			{ key: "populationMinusNetMigration", label: "Bevolking min cum. nettomigratie (gekalibreerd)", format: people },
			{ key: "nativeBackgroundProxy", label: "Inheemse proxy: 2 ouders geboren in NL", format: people },
			{ key: "nativeBackgroundProxyPctPopulation", label: "Inheemse proxy (% bevolking)", format: percent },
			{ key: "migrationBackgroundTotal", label: "Migratieachtergrond totaal", format: people },
			{ key: "migrationBackgroundTotalPctPopulation", label: "Migratieachtergrond (%)", format: percent },
			{ key: "bornAbroadPopulation", label: "In buitenland geboren", format: people },
			{ key: "bornAbroadPopulationPctPopulation", label: "In buitenland geboren (%)", format: percent },
			{ key: "liveBirths", label: "Geboorten", format: people },
			{ key: "deaths", label: "Sterfte", format: people },
			{ key: "birthSurplus", label: "Geboorteoverschot", format: signedPeople },
			{ key: "immigration", label: "Immigratie", format: people },
			{ key: "emigration", label: "Emigratie", format: people },
			{ key: "netMigration", label: "Nettomigratie", format: signedPeople },
			{ key: "netMigrationPctPopulation", label: "Nettomigratie (% bevolking)", format: percent },
		],
	},
	composition: {
		kicker: "Achtergrond en generaties",
		title: "Nederland naar achtergrond",
		leftLabel: "personen",
		rightLabel: "",
		series: [
			{ key: "bornAbroadPopulation", label: "In buitenland geboren", color: "#edae49", axis: "left", kind: "line", width: 2.2, dash: "3 5" },
			{ key: "nativeBackgroundProxy", label: "NL achtergrond / 2 ouders geboren in NL", color: "#235789", axis: "left", kind: "line", width: 3 },
			{ key: "migrationBackgroundTotal", label: "Migratieachtergrond totaal", color: "#8b443d", axis: "left", kind: "line", width: 2.4, dash: "8 4" },
			{ key: "firstGenerationMigrationBackground", label: "1e generatie", color: "#d1495b", axis: "left", kind: "line", width: 2.4 },
			{ key: "secondGenerationMigrationBackground", label: "2e generatie", color: "#2a9d8f", axis: "left", kind: "line", width: 2.4 },
		],
		stats: [
			{ key: "bornAbroadPopulation", label: "In buitenland geboren", format: people },
			{ key: "bornAbroadPopulationPctPopulation", label: "In buitenland geboren (%)", format: percent },
			{ key: "nativeBackgroundProxy", label: "NL achtergrond / 2 ouders geboren in NL", format: people },
			{ key: "nativeBackgroundProxyPctPopulation", label: "NL achtergrond (%)", format: percent },
			{ key: "migrationBackgroundTotal", label: "Migratieachtergrond totaal", format: people },
			{ key: "migrationBackgroundTotalPctPopulation", label: "Migratieachtergrond (%)", format: percent },
			{ key: "firstGenerationMigrationBackground", label: "1e generatie", format: people },
			{ key: "firstGenerationMigrationBackgroundPctPopulation", label: "1e generatie (%)", format: percent },
			{ key: "secondGenerationMigrationBackground", label: "2e generatie", format: people },
			{ key: "secondGenerationMigrationBackgroundPctPopulation", label: "2e generatie (%)", format: percent },
		],
	},
	growth: {
		kicker: "Bevolkingsgroei ontleed",
		title: "Geboorte, migratie en correcties",
		leftLabel: "personen per jaar",
		rightLabel: "",
		series: [
			{ key: "populationGrowth", label: "Totale groei", color: "#235789", axis: "left", kind: "line", width: 3 },
			{ key: "birthSurplus", label: "Geboorteoverschot", color: "#2a9d8f", axis: "left", kind: "bar" },
			{ key: "netMigration", label: "Nettomigratie", color: "#d1495b", axis: "left", kind: "bar" },
			{ key: "otherCorrections", label: "Overige correcties", color: "#8167a9", axis: "left", kind: "line", width: 2.2, dash: "5 5" },
		],
		stats: [
			{ key: "populationGrowth", label: "Totale groei", format: signedPeople },
			{ key: "birthSurplus", label: "Geboorteoverschot", format: signedPeople },
			{ key: "netMigration", label: "Nettomigratie", format: signedPeople },
			{ key: "otherCorrections", label: "Overige correcties", format: signedPeople },
		],
	},
	age: {
		kicker: "Leeftijdsopbouw",
		title: "Samenstelling naar leeftijd",
		leftLabel: "personen",
		rightLabel: "",
		series: [
			{ key: "population", label: "Bevolking", color: "#235789", axis: "left", kind: "bar" },
			{ key: "nativeBackgroundProxy", label: "Inheemse proxy", color: "#8167a9", axis: "left", kind: "bar" },
			{ key: "migrationBackgroundTotal", label: "Migratieachtergrond", color: "#8b443d", axis: "left", kind: "bar" },
			{ key: "firstGenerationMigrationBackground", label: "1e generatie", color: "#d1495b", axis: "left", kind: "bar" },
			{ key: "secondGenerationMigrationBackground", label: "2e generatie", color: "#2a9d8f", axis: "left", kind: "bar" },
		],
		stats: [
			{ key: "population", label: "Bevolking", format: people },
			{ key: "nativeBackgroundProxy", label: "Inheemse proxy", format: people },
			{ key: "migrationBackgroundTotal", label: "Migratieachtergrond", format: people },
			{ key: "firstGenerationMigrationBackground", label: "1e generatie", format: people },
			{ key: "secondGenerationMigrationBackground", label: "2e generatie", format: people },
		],
	},
	origin: {
		kicker: "Herkomst migratie",
		title: "Waar immigranten vandaan komen",
		leftLabel: "personen per jaar",
		rightLabel: "",
		series: [
			{ key: "originImmigrationTotal", label: "Immigratie totaal", color: "#235789", axis: "left", kind: "line", width: 3 },
			{ key: "originDepartureEurope", label: "Vertrekland Europa", color: "#2a9d8f", axis: "left", kind: "bar" },
			{ key: "originDepartureOutsideEurope", label: "Vertrekland buiten Europa", color: "#d1495b", axis: "left", kind: "bar" },
			{ key: "originBornNetherlands", label: "Geboren in NL", color: "#8167a9", axis: "left", kind: "line", width: 2.4, dash: "6 5" },
			{ key: "originDutchNationality", label: "Nederlandse nationaliteit", color: "#edae49", axis: "left", kind: "line", width: 2.2, dash: "2 5" },
		],
		stats: [
			{ key: "originImmigrationTotal", label: "Immigratie totaal", format: people },
			{ key: "originDepartureKnown", label: "Vertrekland bekend", format: people },
			{ key: "originDepartureEurope", label: "Vertrekland Europa", format: people },
			{ key: "originDepartureOutsideEurope", label: "Vertrekland buiten Europa", format: people },
			{ key: "originBornNetherlands", label: "Geboren in NL", format: people },
			{ key: "originBornOutsideNetherlands", label: "Geboren buiten NL", format: people },
			{ key: "originDutchNationality", label: "Nederlandse nationaliteit", format: people },
			{ key: "originNonDutchNationality", label: "Niet-Nederlandse nationaliteit", format: people },
		],
	},
	emigration: {
		kicker: "Emigratie",
		title: "Waar emigranten heen gaan",
		leftLabel: "personen per jaar",
		rightLabel: "",
		series: [
			{ key: "emigrationTotalDetailed", label: "Emigratie totaal", color: "#235789", axis: "left", kind: "line", width: 3 },
			{ key: "emigrationDestinationEurope", label: "Bestemming Europa", color: "#2a9d8f", axis: "left", kind: "bar" },
			{ key: "emigrationDestinationOutsideEurope", label: "Bestemming buiten Europa", color: "#d1495b", axis: "left", kind: "bar" },
			{ key: "emigrationBornNetherlands", label: "Geboren in NL", color: "#8167a9", axis: "left", kind: "line", width: 2.4, dash: "6 5" },
			{ key: "emigrationDutchNationality", label: "Nederlandse nationaliteit", color: "#edae49", axis: "left", kind: "line", width: 2.2, dash: "2 5" },
			{ key: "emigrationAdministrativeRemovals", label: "Administratieve afvoeringen", color: "#8b443d", axis: "left", kind: "line", width: 2, dash: "1 6" },
		],
		stats: [
			{ key: "emigrationTotalDetailed", label: "Emigratie totaal", format: people },
			{ key: "emigrationDestinationReported", label: "Gemeld met bestemming", format: people },
			{ key: "emigrationDestinationKnown", label: "Bestemming gepubliceerd", format: people },
			{ key: "emigrationDestinationEurope", label: "Bestemming Europa", format: people },
			{ key: "emigrationDestinationOutsideEurope", label: "Bestemming buiten Europa", format: people },
			{ key: "emigrationBornNetherlands", label: "Geboren in NL", format: people },
			{ key: "emigrationBornOutsideNetherlands", label: "Geboren buiten NL", format: people },
			{ key: "emigrationDutchNationality", label: "Nederlandse nationaliteit", format: people },
			{ key: "emigrationNonDutchNationality", label: "Niet-Nederlandse nationaliteit", format: people },
			{ key: "emigrationAdministrativeRemovals", label: "Administratieve afvoeringen", format: people },
		],
	},
	motives: {
		kicker: "Migratiemotieven",
		title: "Waarom immigranten komen",
		leftLabel: "personen per immigratiejaar",
		rightLabel: "",
		series: [
			{ key: "migrationPurposeEuWork", label: "EU/EFTA arbeid", color: "#2a9d8f", axis: "left", kind: "line", width: 2.4 },
			{ key: "migrationPurposeEuFamily", label: "EU/EFTA gezin", color: "#235789", axis: "left", kind: "line", width: 2.4 },
			{ key: "migrationPurposeEuStudy", label: "EU/EFTA studie", color: "#edae49", axis: "left", kind: "line", width: 2.4 },
			{ key: "migrationPurposeNonEuWork", label: "Niet-EU/EFTA arbeid", color: "#1b998b", axis: "left", kind: "bar" },
			{ key: "migrationPurposeNonEuFamily", label: "Niet-EU/EFTA gezin", color: "#4f6d7a", axis: "left", kind: "bar" },
			{ key: "migrationPurposeNonEuAsylum", label: "Niet-EU/EFTA asiel", color: "#d1495b", axis: "left", kind: "bar" },
			{ key: "migrationPurposeNonEuTemporaryProtection", label: "Tijdelijke bescherming", color: "#8167a9", axis: "left", kind: "bar" },
		],
		stats: [
			{ key: "migrationPurposeEuTotal", label: "EU/EFTA totaal", format: people },
			{ key: "migrationPurposeEuWork", label: "EU/EFTA arbeid", format: people },
			{ key: "migrationPurposeEuFamily", label: "EU/EFTA gezin", format: people },
			{ key: "migrationPurposeEuStudy", label: "EU/EFTA studie", format: people },
			{ key: "migrationPurposeNonEuTotal", label: "Niet-EU/EFTA totaal", format: people },
			{ key: "migrationPurposeNonEuWork", label: "Niet-EU/EFTA arbeid", format: people },
			{ key: "migrationPurposeNonEuFamily", label: "Niet-EU/EFTA gezin", format: people },
			{ key: "migrationPurposeNonEuAsylum", label: "Niet-EU/EFTA asiel", format: people },
			{ key: "migrationPurposeNonEuTemporaryProtection", label: "Tijdelijke bescherming", format: people },
		],
	},
	housing: {
		kicker: "Woningbouw en tekort",
		title: "Gebouwde woningen versus tekort",
		leftLabel: "woningen",
		rightLabel: "woningvoorraad",
		series: [
			{ key: "newHomes", label: "Nieuwbouw", color: "#2a9d8f", axis: "left", kind: "bar" },
			{ key: "netHousingStockGrowth", label: "Netto voorraadgroei", color: "#e9c46a", axis: "left", kind: "bar" },
			{ key: "housingShortage", label: "Woningtekort", color: "#d1495b", axis: "left", kind: "line", width: 3 },
			{ key: "housingStock", label: "Woningvoorraad", color: "#235789", axis: "right", kind: "line", width: 2.2, dash: "5 5" },
		],
		stats: [
			{ key: "newHomes", label: "Nieuwbouw", format: homes },
			{ key: "netHousingStockGrowth", label: "Netto voorraadgroei", format: homes },
			{ key: "housingShortage", label: "Woningtekort", format: homes },
			{ key: "housingShortagePct", label: "Tekortpercentage", format: percent },
			{ key: "housingStock", label: "Woningvoorraad", format: homes },
			{ key: "personsPerHome", label: "Inwoners per woning", format: personsPerHome },
			{ key: "populationGrowthPerNetHome", label: "Bevolkingsgroei per netto woning", format: decimal },
			{ key: "netHousingStockGrowthPer1000Residents", label: "Netto woningen per 1000 inwoners", format: homesPer1000 },
		],
	},
	grid: {
		kicker: "Stroomnet",
		title: "Wachtrij voor transportcapaciteit",
		leftLabel: "unieke verzoeken",
		rightLabel: "MW in wachtrij",
		series: [
			{ key: "gridAfnameRequests", label: "Afname verzoeken", color: "#d1495b", axis: "left", kind: "bar" },
			{ key: "gridInvoedingRequests", label: "Invoeding verzoeken", color: "#f4a261", axis: "left", kind: "bar" },
			{ key: "gridAfnameMw", label: "Afname MW", color: "#235789", axis: "right", kind: "line", width: 3 },
			{ key: "gridInvoedingMw", label: "Invoeding MW", color: "#2a9d8f", axis: "right", kind: "line", width: 3 },
		],
		stats: [
			{ key: "gridAfnameRequests", label: "Afname verzoeken", format: requests },
			{ key: "gridAfnameMw", label: "Afname wachtrij", format: mw },
			{ key: "gridInvoedingRequests", label: "Invoeding verzoeken", format: requests },
			{ key: "gridInvoedingMw", label: "Invoeding wachtrij", format: mw },
		],
	},
};
